version: '3.8'
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        ports:
            - 8080:8080
        volumes:
            - .:/go/src