version: '3'

tasks:
  build:
    cmds:
      - docker-compose up --build -d
  up:
    cmds:
      - docker-compose up -d
  rbuild:
    cmds:
      - task stop
      - task build
  stop:
    cmds:
      - docker stop server
  srv-e:
    cmds:
      - docker exec -it server sh
  run-srv:
    cmds:
      - docker-compose exec server go run main.go